
const mongoose = require('mongoose');
const Product = require('./models/Product');
require('dotenv').config();

// Sample product data matching frontend structure
const sampleProducts = [
  {
    id: "product1",
    name: "Premium Cashews",
    price: 150000,
    image: [
      "https://5.imimg.com/data5/JW/HP/MY-39690665/premium-cashew-nut-500x500.jpg",
      "https://d3kgrlupo77sg7.cloudfront.net/media/chococoorgspice.com/images/products/organic-coorg-cashew-nuts-500-gm-coorg-dry-fruits-whole-big-size.20220919003557.webp",
      "https://kanwarjis.in/cdn/shop/files/Cashew3.webp?v=1727696207",
      "https://royalfantasy.in/cdn/shop/products/Cashew-Nuts-Small-1.jpg?v=1627471481"
    ],
    category: "dry fruits",
    company: "HealthyBites",
    description: "High-quality premium cashews with a rich taste.",
    colors: ["#ff0000"],
    stock: 8,
    numReviews: 150,
    rating: 4.9,
    featured: true,
    shipping: true,
    variants: [
      { weight: '250g', price: 45000, stock: 20 },
      { weight: '500g', price: 85000, stock: 15 },
      { weight: '1kg', price: 150000, stock: 8 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 553,
      protein: 18,
      totalFat: 44,
      saturatedFat: 8,
      unsaturatedFat: 32,
      carbohydrates: 30,
      fiber: 3.3,
      sugars: 6,
      iron: 6.7,
      calcium: 37,
      magnesium: 292,
      zinc: 5.8,
      potassium: 660,
      phosphorus: 593,
      copper: 2.2,
      selenium: 20,
      vitaminE: 0.9,
      vitaminB1: 0.42,
      vitaminB6: 0.42,
      folate: 25,
      healthTags: ['high-protein', 'iron-rich', 'energy-boost', 'heart-healthy'],
      healthBenefits: ['Supports muscle growth', 'Boosts energy levels', 'Good for heart health', 'Rich in minerals'],
      allergens: ['tree-nuts'],
      servingSize: '100g'
    }
  },
  {
    id: "product2",
    name: "Organic Almonds",
    price: 120000,
    image: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSot_aTLnVz8sRdgRj76HbkEe-8Ei1tKToEHA&s",
      "https://www.greendna.in/cdn/shop/products/almond2_1200x1200.jpeg?v=1564303633",
      "https://cowberry-static.s3.ap-south-1.amazonaws.com/static/uploads/products/cowberry-6682649521733374165.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVsn9mJP1eFnWFBycA1A7bKbPGw_X4XPu6jw&s"
    ],
    category: "nuts",
    company: "NuttyDelight",
    description: "Fresh organic almonds packed with nutrients.",
    colors: ["#000"],
    stock: 8,
    numReviews: 120,
    rating: 4.5,
    featured: false,
    shipping: true,
    variants: [
      { weight: '250g', price: 35000, stock: 25 },
      { weight: '500g', price: 65000, stock: 18 },
      { weight: '1kg', price: 120000, stock: 8 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 579,
      protein: 21,
      totalFat: 50,
      saturatedFat: 4,
      unsaturatedFat: 42,
      carbohydrates: 22,
      fiber: 12.5,
      sugars: 4,
      iron: 3.7,
      calcium: 269,
      magnesium: 270,
      zinc: 3.1,
      potassium: 733,
      phosphorus: 481,
      copper: 1.0,
      selenium: 4,
      vitaminE: 25.6,
      vitaminB1: 0.2,
      vitaminB6: 0.14,
      folate: 44,
      healthTags: ['high-protein', 'high-fiber', 'heart-healthy', 'brain-health', 'bone-health'],
      healthBenefits: ['Excellent for brain health', 'Supports bone strength', 'Rich in Vitamin E', 'Heart-healthy fats'],
      allergens: ['tree-nuts'],
      servingSize: '100g'
    }
  },
  {
    id: "product3",
    name: "Natural Walnuts",
    price: 170000,
    image: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA0PO9XYcGyd4Dxuos6IThn4EKFSo44l5FPA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6qIX6hXySwBhDa3qNAkGnRZ5sX0pm_x-1gQ&s",
      "https://images-prod.healthline.com/hlcmsresource/images/AN_images/benefits-of-walnuts-1296x728-feature.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqwtMgQjpd-BTAR47DSHsP80SmUlHlaZEGUg&s"
    ],
    category: "nuts",
    company: "Nature's Basket",
    description: "Rich and crunchy walnuts full of omega-3s.",
    colors: ["#22D3EF"],
    stock: 5,
    numReviews: 125,
    rating: 4.2,
    featured: true,
    shipping: false,
    variants: [
      { weight: '250g', price: 50000, stock: 12 },
      { weight: '500g', price: 95000, stock: 10 },
      { weight: '1kg', price: 170000, stock: 5 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 654,
      protein: 15,
      totalFat: 65,
      saturatedFat: 6,
      unsaturatedFat: 56,
      carbohydrates: 14,
      fiber: 6.7,
      sugars: 3,
      iron: 2.9,
      calcium: 98,
      magnesium: 158,
      zinc: 3.1,
      potassium: 441,
      phosphorus: 346,
      copper: 1.6,
      selenium: 5,
      vitaminE: 0.7,
      vitaminB1: 0.34,
      vitaminB6: 0.54,
      folate: 98,
      healthTags: ['brain-health', 'heart-healthy', 'high-fiber'],
      healthBenefits: ['Rich in Omega-3 fatty acids', 'Excellent for brain function', 'Supports heart health', 'Anti-inflammatory'],
      allergens: ['tree-nuts'],
      servingSize: '100g'
    }
  },
  {
    id: "product4",
    name: "Dried Figs",
    price: 140000,
    image: [
      "https://www.greendna.in/cdn/shop/files/dryfig6_600x.jpg?v=1710672994",
      "https://ayoubs.ca/cdn/shop/articles/dried_figs_520x500_520x500_2f44883e-6fe8-4993-b160-f7df8dcd8d3f_500x.png?v=1744047961",
      "https://fairfieldcheese.com/cdn/shop/products/Untitleddesign_11.png?v=1630964430&width=600"
    ],
    category: "dry fruits",
    company: "Fruit Harvest",
    description: "Sweet and chewy dried figs perfect for snacking.",
    colors: ["#CDD0D0"],
    stock: 6,
    numReviews: 96,
    rating: 4.0,
    featured: false,
    shipping: true,
    variants: [
      { weight: '250g', price: 40000, stock: 15 },
      { weight: '500g', price: 75000, stock: 12 },
      { weight: '1kg', price: 140000, stock: 6 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 249,
      protein: 3,
      totalFat: 1,
      saturatedFat: 0.2,
      unsaturatedFat: 0.6,
      carbohydrates: 64,
      fiber: 9.8,
      sugars: 48,
      iron: 2,
      calcium: 162,
      magnesium: 68,
      zinc: 0.5,
      potassium: 680,
      phosphorus: 67,
      copper: 0.3,
      selenium: 0,
      vitaminE: 0.4,
      vitaminB1: 0.09,
      vitaminB6: 0.11,
      folate: 9,
      healthTags: ['high-fiber', 'bone-health', 'energy-boost'],
      healthBenefits: ['High in dietary fiber', 'Supports bone health', 'Natural energy booster', 'Rich in calcium'],
      allergens: [],
      servingSize: '100g'
    }
  },
  {
    id: "product5",
    name: "Dry-Dates",
    price: 160000,
    image: [
      "https://www.aldahome.com/media/catalog/product/p/r/premium-red-dry-dates-chuhara.jpg",
      "https://daivikorganic.com/cdn/shop/products/4_45136c9c-702e-4916-acf8-448330f32134.png?v=1670409164",
      "https://marudharmewa.com/cdn/shop/files/C5D_3949.webp?v=1715949146",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoMHp-es0nv6HBONn_pIg3KD1-BJbDIdr6MA&s"
    ],
    category: "dry-dates",
    company: "CrunchyDelight",
    description: "Lightly salted roasted cashews with a crunchy texture.",
    colors: ["#000"],
    stock: 4,
    numReviews: 89,
    rating: 4.6,
    featured: true,
    shipping: true,
    variants: [
      { weight: '250g', price: 45000, stock: 20 },
      { weight: '500g', price: 85000, stock: 10 },
      { weight: '1kg', price: 160000, stock: 4 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 282,
      protein: 2.5,
      totalFat: 0.4,
      saturatedFat: 0.1,
      unsaturatedFat: 0.2,
      carbohydrates: 75,
      fiber: 8,
      sugars: 63,
      iron: 1.0,
      calcium: 64,
      magnesium: 54,
      zinc: 0.4,
      potassium: 656,
      phosphorus: 62,
      copper: 0.4,
      selenium: 3,
      vitaminE: 0,
      vitaminB1: 0.05,
      vitaminB6: 0.25,
      folate: 19,
      healthTags: ['energy-boost', 'high-fiber', 'iron-rich'],
      healthBenefits: ['Natural sweetener', 'Quick energy source', 'Good for digestion', 'Rich in potassium'],
      allergens: [],
      servingSize: '100g'
    }
  },
  {
    id: "product6",
    name: "Dry Fruits Hamper",
    price: 180000,
    image: [
      "https://images.prestogifts.com/upload/Gift-Combos/Gift-Hampers/GH06/1431X1431/62dae23212c13_1a.jpg",
      "https://snaktime.in/images/chocolates/new-year-gift-hamper-with-dry-fruits-1.jpg",
      "https://m.media-amazon.com/images/I/91IVJBUPCBL.jpg",
      "https://www.zupppy.com/wp-content/uploads/2024/03/WhatsApp-Image-2024-03-29-at-13.38.16_ac4d0ec6.jpg"
    ],
    category: "dry fruits",
    company: "NuttyFlavors",
    description: "Spicy flavored cashews for an extra zing.",
    colors: ["#ff0000"],
    stock: 9,
    numReviews: 98,
    rating: 4.8,
    featured: false,
    shipping: false,
    variants: [
      { weight: '500g', price: 90000, stock: 15 },
      { weight: '1kg', price: 180000, stock: 9 },
      { weight: '2kg', price: 340000, stock: 5 }
    ],
    defaultWeight: '1kg',
    nutritionInfo: {
      calories: 520,
      protein: 15,
      totalFat: 38,
      saturatedFat: 5,
      unsaturatedFat: 30,
      carbohydrates: 35,
      fiber: 6,
      sugars: 18,
      iron: 4.5,
      calcium: 120,
      magnesium: 180,
      zinc: 3.2,
      potassium: 580,
      phosphorus: 380,
      copper: 1.2,
      selenium: 10,
      vitaminE: 8,
      vitaminB1: 0.3,
      vitaminB6: 0.35,
      folate: 35,
      healthTags: ['high-protein', 'energy-boost', 'heart-healthy'],
      healthBenefits: ['Premium gift pack', 'Mix of essential nutrients', 'Heart-healthy fats', 'Perfect for gifting'],
      allergens: ['tree-nuts'],
      servingSize: '100g'
    }
  },
  {
    id: "product7",
    name: "Flavored Cashews - Honey Roasted",
    price: 190000,
    image: [
      "https://www.beyondthechickencoop.com/wp-content/uploads/2022/05/Honey-Roasted-Cashews.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2022/5/NE/JH/BJ/152317219/flavored-cashew-png.png",
      "https://thebellyrulesthemind.net/wp-content/uploads/2021/02/Roasted-cashew-nuts-3-flavors-5-720x720.png",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRd_2CllPC1UtefJCRdFYBiYUY3TygIcflG3A&s"
    ],
    category: "flavored cashews",
    company: "NuttyFlavors",
    description: "Sweet honey-roasted cashews for a delicious treat.",
    colors: ["#22D3EF"],
    stock: 6,
    numReviews: 115,
    rating: 4.2,
    featured: true,
    shipping: true,
    variants: [
      { weight: '250g', price: 55000, stock: 18 },
      { weight: '500g', price: 100000, stock: 12 },
      { weight: '1kg', price: 190000, stock: 6 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 580,
      protein: 16,
      totalFat: 42,
      saturatedFat: 7,
      unsaturatedFat: 32,
      carbohydrates: 38,
      fiber: 3,
      sugars: 18,
      iron: 5.8,
      calcium: 40,
      magnesium: 250,
      zinc: 5,
      potassium: 580,
      phosphorus: 500,
      copper: 2,
      selenium: 18,
      vitaminE: 1,
      vitaminB1: 0.4,
      vitaminB6: 0.4,
      folate: 22,
      healthTags: ['high-protein', 'energy-boost', 'iron-rich'],
      healthBenefits: ['Delicious honey flavor', 'Great energy snack', 'Rich in minerals', 'Satisfying crunch'],
      allergens: ['tree-nuts'],
      servingSize: '100g'
    }
  },
  {
    id: "product8",
    name: "Trail Mix",
    price: 160000,
    image: [
      "https://www.aromaco.com/wp-content/uploads/2021/08/OrangeQuoteCatsFacebookCover28129-1200x676.png",
      "https://www.eatingbirdfood.com/wp-content/uploads/2022/11/superfood-trail-mix-hero.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZrN2rCfRM3KiqAfFXooRkTwBbCEvDyfEqI2cjZSkQT0V5dkcJ2elm9eRJAjt9go_KsPs&usqp=CAU",
      "https://feelgoodfoodie.net/wp-content/uploads/2024/06/Trail-Mix-08.jpg"
    ],
    category: "snacks",
    company: "HealthyBites",
    description: "A healthy mix of nuts, seeds, and dried fruits.",
    colors: ["#22D3EF"],
    stock: 7,
    numReviews: 96,
    rating: 4.0,
    featured: true,
    shipping: true,
    variants: [
      { weight: '250g', price: 45000, stock: 20 },
      { weight: '500g', price: 85000, stock: 15 },
      { weight: '1kg', price: 160000, stock: 7 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 462,
      protein: 14,
      totalFat: 29,
      saturatedFat: 4,
      unsaturatedFat: 22,
      carbohydrates: 44,
      fiber: 5.2,
      sugars: 28,
      iron: 3.5,
      calcium: 68,
      magnesium: 118,
      zinc: 2.8,
      potassium: 548,
      phosphorus: 256,
      copper: 0.6,
      selenium: 8,
      vitaminE: 4.2,
      vitaminB1: 0.28,
      vitaminB6: 0.18,
      folate: 22,
      healthTags: ['energy-boost', 'immunity-boost'],
      healthBenefits: ['Quick energy source', 'Perfect for hiking', 'Mix of nutrients', 'Boosts immunity'],
      allergens: ['tree-nuts', 'peanuts'],
      servingSize: '100g'
    }
  },
  {
    id: "product9",
    name: "Granola Bars",
    price: 80000,
    image: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4VGqFK--IWCbgPLTukmOtiXm_w-pT6sV2VQ&s",
      "https://www.paleorunningmomma.com/wp-content/uploads/2021/03/peanut-butter-granola-bars-5.jpg",
      "https://www.redpathsugar.com/sites/redpathsugar_com/files/styles/m/public/2024-08/No_Bake_Granola_Bars-600x400.jpg.webp?itok=QdpX2AI9",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTptK4S9Xqm3zZZgzkYq30smIpOTM0BOfTYre_kdf1-SSQzhyEH2nJoQajrfToPezmnVs4&usqp=CAU"
    ],
    category: "snacks",
    company: "NuttyDelight",
    description: "Crunchy granola bars for a quick energy boost.",
    colors: ["#CDD0D0"],
    stock: 8,
    numReviews: 122,
    rating: 4.6,
    featured: false,
    shipping: true,
    variants: [
      { weight: '100g', price: 25000, stock: 30 },
      { weight: '250g', price: 45000, stock: 20 },
      { weight: '500g', price: 80000, stock: 8 }
    ],
    defaultWeight: '250g',
    nutritionInfo: {
      calories: 420,
      protein: 8,
      totalFat: 18,
      saturatedFat: 3,
      unsaturatedFat: 12,
      carbohydrates: 58,
      fiber: 6,
      sugars: 22,
      iron: 3,
      calcium: 50,
      magnesium: 80,
      zinc: 2,
      potassium: 320,
      phosphorus: 180,
      copper: 0.4,
      selenium: 5,
      vitaminE: 3,
      vitaminB1: 0.25,
      vitaminB6: 0.2,
      folate: 18,
      healthTags: ['energy-boost', 'high-fiber'],
      healthBenefits: ['Quick energy boost', 'Healthy snacking', 'Good source of fiber', 'Perfect on-the-go'],
      allergens: ['tree-nuts', 'gluten'],
      servingSize: '100g'
    }
  },
  {
    id: "product10",
    name: "Roasted Chickpeas",
    price: 100000,
    image: [
      "https://www.eatingwell.com/thmb/U9XX4O3Ds4geco7uTt-t6LeKsYE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Spice-Roasted-Chickpeas-2-454859750de34b71bb8c900d35852844.jpg"
    ],
    category: "snacks",
    company: "Golden Harvest",
    description: "Crunchy roasted chickpeas seasoned to perfection.",
    colors: ["#000"],
    stock: 6,
    numReviews: 88,
    rating: 4.7,
    featured: false,
    shipping: false,
    variants: [
      { weight: '250g', price: 30000, stock: 25 },
      { weight: '500g', price: 55000, stock: 15 },
      { weight: '1kg', price: 100000, stock: 6 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 380,
      protein: 20,
      totalFat: 6,
      saturatedFat: 0.6,
      unsaturatedFat: 4,
      carbohydrates: 58,
      fiber: 17,
      sugars: 4,
      iron: 6.2,
      calcium: 100,
      magnesium: 115,
      zinc: 3.4,
      potassium: 875,
      phosphorus: 366,
      copper: 0.85,
      selenium: 8,
      vitaminE: 0.8,
      vitaminB1: 0.48,
      vitaminB6: 0.54,
      folate: 557,
      healthTags: ['high-protein', 'high-fiber', 'iron-rich', 'weight-loss'],
      healthBenefits: ['High plant protein', 'Excellent fiber source', 'Supports weight loss', 'Low fat snack'],
      allergens: [],
      servingSize: '100g'
    }
  },
  {
    id: "product11",
    name: "Pistachios",
    price: 180000,
    image: [
      "https://images.healthshots.com/healthshots/en/uploads/2023/09/04073149/pistachip-1600x900.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUtAIDhVm8nSd7nm18oLigkeYQcu0_2Fv1jQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbpNqpe6cBBgnN8JkB9z_wYCOb_PYbQh6LBA&s",
      "https://nuttygritties.com/cdn/shop/products/71zUpdUXAPL._SX679_8a2400f6-48e2-4f45-bd8b-90219558d476_1024x1024.jpg?v=1704713139",
      "https://images-cdn.ubuy.co.in/667df3105590fa2fca56fc5f-wonderful-roasted-salted-pistachios.jpg"
    ],
    category: "nuts",
    company: "NuttyDelight",
    description: "Fresh pistachios with a delicious crunch.",
    colors: ["#22D3EF"],
    stock: 9,
    variants: [
      { weight: '250g', price: 55000, stock: 20 },
      { weight: '500g', price: 100000, stock: 15 },
      { weight: '1kg', price: 180000, stock: 9 }
    ],
    defaultWeight: '500g',
    numReviews: 89,
    rating: 4.8,
    featured: true,
    shipping: false,
    nutritionInfo: {
      calories: 560,
      protein: 20,
      totalFat: 45,
      saturatedFat: 5.5,
      unsaturatedFat: 37,
      carbohydrates: 28,
      fiber: 10.6,
      sugars: 8,
      iron: 3.9,
      calcium: 105,
      magnesium: 121,
      zinc: 2.2,
      potassium: 1025,
      phosphorus: 490,
      copper: 1.3,
      selenium: 7,
      vitaminE: 2.9,
      vitaminB1: 0.87,
      vitaminB6: 1.7,
      folate: 51,
      healthTags: ['high-protein', 'high-fiber', 'heart-healthy', 'weight-loss'],
      healthBenefits: ['Supports weight management', 'Good for eye health', 'Heart-healthy snack', 'High in antioxidants'],
      allergens: ['tree-nuts'],
      servingSize: '100g'
    }
  },
  {
    id: "product12",
    name: "Raisins",
    price: 120000,
    image: [
      "https://images.meesho.com/images/products/295937458/qra1i_512.webp",
      "https://www.sendbestgift.com/assets/images/product/Raisins.jpg",
      "https://cdn-prod.medicalnewstoday.com/content/images/articles/325/325127/raisins-on-a-wooden-spoon.jpg",
      "https://d146hunxuupfmg.cloudfront.net/blog_images/black_raisins.webp"
    ],
    category: "dry fruits",
    company: "Golden Harvest",
    description: "Naturally sweet raisins for a healthy snack.",
    colors: ["#ff0000"],
    stock: 8,
    numReviews: 115,
    rating: 4.9,
    featured: false,
    shipping: true,
    variants: [
      { weight: '250g', price: 35000, stock: 25 },
      { weight: '500g', price: 65000, stock: 18 },
      { weight: '1kg', price: 120000, stock: 8 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 299,
      protein: 3.1,
      totalFat: 0.5,
      saturatedFat: 0.1,
      unsaturatedFat: 0.3,
      carbohydrates: 79,
      fiber: 3.7,
      sugars: 59,
      iron: 1.9,
      calcium: 50,
      magnesium: 32,
      zinc: 0.2,
      potassium: 749,
      phosphorus: 101,
      copper: 0.3,
      selenium: 0.6,
      vitaminE: 0.1,
      vitaminB1: 0.11,
      vitaminB6: 0.17,
      folate: 5,
      healthTags: ['energy-boost', 'iron-rich'],
      healthBenefits: ['Natural energy booster', 'Good for digestion', 'Rich in antioxidants', 'Supports bone health'],
      allergens: [],
      servingSize: '100g'
    }
  },
  {
    id: "product13",
    name: "Dry Fruit Energy Bites",
    price: 95000,
    image: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjKoTsw_UdoBjKeobJF3WaVUn1_temwx7lAg&s",
      "https://withsaltandwit.com/wp-content/uploads/2015/01/Fruit-Nut-Trail-Mix-Energy-Bites_-5.jpg",
      "https://www.layersofhappiness.com/wp-content/uploads/2014/05/HealthyAlmond-Energy-Balls.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7Y3z9bj7IBj5vhIYk9j9Cxb0HmwTASy04iQ&s"
    ],
    category: "sweets",
    company: "CrunchyDelight",
    description: "Hand Made product. Authentic product.",
    colors: ["#F5DEB3"],
    stock: 10,
    numReviews: 250,
    rating: 4.9,
    featured: true,
    shipping: true,
    variants: [
      { weight: '250g', price: 30000, stock: 25 },
      { weight: '500g', price: 55000, stock: 15 },
      { weight: '1kg', price: 95000, stock: 10 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 450,
      protein: 12,
      totalFat: 28,
      saturatedFat: 4,
      unsaturatedFat: 20,
      carbohydrates: 42,
      fiber: 5,
      sugars: 20,
      iron: 4,
      calcium: 80,
      magnesium: 120,
      zinc: 2.5,
      potassium: 450,
      phosphorus: 280,
      copper: 0.8,
      selenium: 8,
      vitaminE: 5,
      vitaminB1: 0.2,
      vitaminB6: 0.25,
      folate: 25,
      healthTags: ['energy-boost', 'high-protein'],
      healthBenefits: ['Power-packed energy bites', 'Mix of dry fruits', 'No added sugar', 'Natural sweetness'],
      allergens: ['tree-nuts'],
      servingSize: '100g'
    }
  },
  {
    id: "product14",
    name: "Kaju Katli Dry Fruit Sweet",
    price: 155000,
    image: [
      "https://jainvijay.in/img/Products/sweet/regular%20items/dry%20fruit%20kaju%20katri/Bg.jpg",
      "https://www.shreemithai.com/cdn/shop/products/kaju-dry-fruit-burfi-773541.jpg?v=1707819886&width=700",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_dm9xi6pRlAbIWeEdWNsQjewPgnN39gCLUQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzIip4f76fb2Yjumr0ueAtC3CtdZU5XSV5yQ&s"
    ],
    category: "sweets",
    company: "HealthyBites",
    description: "Hand Made product. Authentic product.",
    colors: ["#F5DEB3"],
    stock: 15,
    numReviews: 230,
    rating: 4.8,
    featured: true,
    shipping: true,
    variants: [
      { weight: '250g', price: 45000, stock: 30 },
      { weight: '500g', price: 85000, stock: 20 },
      { weight: '1kg', price: 155000, stock: 15 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 540,
      protein: 14,
      totalFat: 32,
      saturatedFat: 6,
      unsaturatedFat: 24,
      carbohydrates: 52,
      fiber: 2,
      sugars: 38,
      iron: 5,
      calcium: 40,
      magnesium: 200,
      zinc: 4,
      potassium: 500,
      phosphorus: 400,
      copper: 1.5,
      selenium: 15,
      vitaminE: 0.8,
      vitaminB1: 0.35,
      vitaminB6: 0.35,
      folate: 20,
      healthTags: ['high-protein', 'iron-rich'],
      healthBenefits: ['Traditional Indian sweet', 'Rich in cashew nutrients', 'Festive delicacy', 'Handmade quality'],
      allergens: ['tree-nuts', 'dairy'],
      servingSize: '100g'
    }
  },
  {
    id: "product15",
    name: "Stuffed Dates with Almonds",
    price: 120000,
    image: [
      "https://img.taste.com.au/zrJDqpk8/taste/2016/11/almond-stuffed-dates-6748-1.jpeg",
      "https://images.eatthismuch.com/med/343996_tabitharwheeler_de1a76c5-083f-4a38-939b-00c85f1f4187.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjSoU2EK0ssGwrif1yQvM3TVSfM68uSXMVqw&s",
      "https://www.unicornsinthekitchen.com/wp-content/uploads/2018/06/stuffed-dates-sq.jpg"
    ],
    category: "dry fruits",
    company: "CrunchyDelight",
    description: "High-quality premium dry fruits with a rich taste.",
    colors: ["#F5DEB3"],
    stock: 10,
    numReviews: 150,
    rating: 4.3,
    featured: true,
    shipping: true,
    variants: [
      { weight: '250g', price: 35000, stock: 20 },
      { weight: '500g', price: 65000, stock: 15 },
      { weight: '1kg', price: 120000, stock: 10 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 340,
      protein: 8,
      totalFat: 12,
      saturatedFat: 1,
      unsaturatedFat: 9,
      carbohydrates: 52,
      fiber: 7,
      sugars: 42,
      iron: 2.5,
      calcium: 100,
      magnesium: 80,
      zinc: 1.2,
      potassium: 620,
      phosphorus: 150,
      copper: 0.5,
      selenium: 2,
      vitaminE: 6,
      vitaminB1: 0.12,
      vitaminB6: 0.2,
      folate: 15,
      healthTags: ['energy-boost', 'brain-health', 'high-fiber'],
      healthBenefits: ['Perfect combination', 'Natural energy', 'Brain-boosting almonds', 'Digestive support'],
      allergens: ['tree-nuts'],
      servingSize: '100g'
    }
  },
  {
    id: "product16",
    name: "Dry Fruit Laddu",
    price: 135000,
    image: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwVzdpdKMRhrLOLlo0b_sqjyl0fwoyEqJxnQ&s",
      "https://www.cookclickndevour.com/wp-content/uploads/2019/09/dry-fruits-laddu-recipe-2.jpg",
      "https://patnamlopalleruchulu.in/wp-content/uploads/2024/09/Dry-fruits-laddu-560x580.png",
      "https://www.kartiksmithai.com/cdn/shop/products/Untitleddesign-2022-03-15T175707.965.png?v=1647352412"
    ],
    category: "sweets",
    company: "HealthyBites",
    description: "High-quality premium dry fruits laddu with a rich taste.",
    colors: ["#F5DEB3"],
    stock: 15,
    numReviews: 220,
    rating: 4.7,
    featured: true,
    shipping: true,
    variants: [
      { weight: '250g', price: 40000, stock: 25 },
      { weight: '500g', price: 75000, stock: 20 },
      { weight: '1kg', price: 135000, stock: 15 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 480,
      protein: 10,
      totalFat: 25,
      saturatedFat: 8,
      unsaturatedFat: 15,
      carbohydrates: 56,
      fiber: 4,
      sugars: 32,
      iron: 3.5,
      calcium: 90,
      magnesium: 100,
      zinc: 2,
      potassium: 400,
      phosphorus: 250,
      copper: 0.7,
      selenium: 6,
      vitaminE: 4,
      vitaminB1: 0.18,
      vitaminB6: 0.22,
      folate: 18,
      healthTags: ['energy-boost', 'high-protein'],
      healthBenefits: ['Traditional healthy sweet', 'Mix of dry fruits', 'Rich in ghee nutrition', 'Festive favorite'],
      allergens: ['tree-nuts', 'dairy'],
      servingSize: '100g'
    }
  },
  {
    id: "product17",
    name: "Hazelnuts",
    price: 165000,
    image: [
      "https://www.greendna.in/cdn/shop/products/hnut.jpg?v=1567521689",
      "https://www.greendna.in/cdn/shop/products/hnut.jpg?v=1567521689",
      "https://thebakingtools.com/cdn/shop/files/thebakingtools-com-50-grams-hazelnut-kernels-38545125703868.png?v=1742652385",
      "https://cdn.shopify.com/s/files/1/0437/8953/files/Hazelnuts.png?v=1652477908"
    ],
    category: "dry fruits",
    company: "HealthyBites",
    description: "High-quality hazelnuts.",
    colors: ["#F5DEB3"],
    stock: 7,
    numReviews: 160,
    rating: 4.2,
    featured: true,
    shipping: true,
    variants: [
      { weight: '250g', price: 50000, stock: 18 },
      { weight: '500g', price: 90000, stock: 12 },
      { weight: '1kg', price: 165000, stock: 7 }
    ],
    defaultWeight: '500g',
    nutritionInfo: {
      calories: 628,
      protein: 15,
      totalFat: 61,
      saturatedFat: 4.5,
      unsaturatedFat: 52,
      carbohydrates: 17,
      fiber: 9.7,
      sugars: 4.3,
      iron: 4.7,
      calcium: 114,
      magnesium: 163,
      zinc: 2.5,
      potassium: 680,
      phosphorus: 290,
      copper: 1.7,
      selenium: 2.4,
      vitaminE: 15,
      vitaminB1: 0.64,
      vitaminB6: 0.56,
      folate: 113,
      healthTags: ['heart-healthy', 'brain-health', 'high-fiber', 'iron-rich'],
      healthBenefits: ['Excellent for heart', 'Rich in Vitamin E', 'Supports brain function', 'High in healthy fats'],
      allergens: ['tree-nuts'],
      servingSize: '100g'
    }
  },
  {
    id: "product18",
    name: "Pine Nuts (Chilgoza)",
    price: 90000,
    image: [
      "https://staticimg.amarujala.com/assets/images/2024/09/28/chilgoza_a25fde0cf512bf041e02955bcbd5c473.jpeg?w=1200",
      "https://www.thukralfoods.com/wp-content/uploads/2022/03/pine-nuts-unshelled-600x400.jpg",
      "https://triphal.com/cdn/shop/files/1220212000041_1.jpg?v=1686831785&width=1445",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrucrzJv0WHs_oPcVAj1sbI0JZyMupiyVRdg&s"
    ],
    category: "dry fruits",
    company: "Golden Harvest",
    description: "High-quality premium Pine Nuts.",
    colors: ["#F5DEB3"],
    stock: 5,
    numReviews: 120,
    rating: 4.1,
    variants: [
      { weight: '100g', price: 25000, stock: 15 },
      { weight: '250g', price: 55000, stock: 10 },
      { weight: '500g', price: 90000, stock: 5 }
    ],
    defaultWeight: '250g',
    featured: true,
    shipping: true,
    nutritionInfo: {
      calories: 673,
      protein: 14,
      totalFat: 68,
      saturatedFat: 5,
      unsaturatedFat: 58,
      carbohydrates: 13,
      fiber: 3.7,
      sugars: 3.6,
      iron: 5.5,
      calcium: 16,
      magnesium: 251,
      zinc: 6.4,
      potassium: 597,
      phosphorus: 575,
      copper: 1.3,
      selenium: 0.7,
      vitaminE: 9.3,
      vitaminB1: 0.36,
      vitaminB6: 0.09,
      folate: 34,
      healthTags: ['heart-healthy', 'brain-health', 'iron-rich', 'high-protein'],
      healthBenefits: ['Premium pine nuts', 'Rich in healthy fats', 'Supports metabolism', 'Eye health support'],
      allergens: ['tree-nuts'],
      servingSize: '100g'
    }
  },
  {
    id: "product19",
    name: "Organic Blueberries",
    price: 600000,
    image: [
      "https://m.media-amazon.com/images/I/71oJlHDge3L.jpg",
      "https://cdn.shopaccino.com/rootz/products/blueberry-2-361710558531335_m.jpg?v=562",
      "https://image.made-in-china.com/202f0j00uUrkbpngqDzI/Natural-Organic-Freeze-Dried-Wild-Blueberry-Fruit-Juice-Powder.webp",
      "https://images.squarespace-cdn.com/content/v1/58ebe6632994ca71ba304549/1491938746710-RE9ICCSBHSDYRFNJU5WG/image-asset.jpeg"
    ],
    category: "berries",
    company: "HealthyBites",
    description: "High-quality Organic Blueberries with a rich taste.",
    colors: ["#4169E1"],
    stock: 9,
    numReviews: 180,
    rating: 4.9,
    featured: true,
    shipping: false,
    nutritionInfo: {
      calories: 317,
      protein: 3,
      totalFat: 1.2,
      saturatedFat: 0.1,
      unsaturatedFat: 0.8,
      carbohydrates: 76,
      fiber: 12,
      sugars: 56,
      iron: 2.8,
      calcium: 57,
      magnesium: 30,
      zinc: 0.5,
      potassium: 620,
      phosphorus: 52,
      copper: 0.3,
      selenium: 0.2,
      vitaminE: 3.5,
      vitaminB1: 0.07,
      vitaminB6: 0.1,
      folate: 12,
      healthTags: ['brain-health', 'immunity-boost', 'high-fiber'],
      healthBenefits: ['Powerful antioxidants', 'Supports brain health', 'Boosts immunity', 'Anti-aging properties'],
      allergens: [],
      servingSize: '100g'
    }
  },
  {
    id: "product20",
    name: "Organic Cranberries",
    price: 150000,
    image: [
      "https://www.melissas.com/cdn/shop/files/image-of-organic-cranberries-fruit-1125637327_600x600.jpg?v=1738768960",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbwDLTRoz1KdqIVOOlpPSnA3tjdnQgfGzjpA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbLTinPzNvk2fOboHwpqQxFvTSKDELVR5D6A&s",
      "https://satopradhan.com/cdn/shop/products/cranberries-whole-dried-organically-cultivated-and-naturally-dehydrated-in-200g-pack-unsweetened-and-unsulphured-without-synthetic-flavourscolors-or-chemical-preservatives-satopradhan-2-31584937115874_728x728.jpg?v=1702970694"
    ],
    category: "berries",
    company: "HealthyBites",
    description: "High-quality Organic Cranberries with a rich taste.",
    colors: ["#DC143C"],
    stock: 6,
    numReviews: 110,
    rating: 4.2,
    featured: true,
    shipping: false,
    nutritionInfo: {
      calories: 308,
      protein: 0.4,
      totalFat: 1.4,
      saturatedFat: 0.1,
      unsaturatedFat: 1,
      carbohydrates: 82,
      fiber: 5.7,
      sugars: 65,
      iron: 0.5,
      calcium: 10,
      magnesium: 8,
      zinc: 0.1,
      potassium: 49,
      phosphorus: 16,
      copper: 0.1,
      selenium: 0.6,
      vitaminE: 2.1,
      vitaminB1: 0.02,
      vitaminB6: 0.06,
      folate: 2,
      healthTags: ['immunity-boost', 'high-fiber'],
      healthBenefits: ['UTI prevention', 'Rich in antioxidants', 'Supports immune system', 'Heart health support'],
      allergens: [],
      servingSize: '100g'
    }
  }
];

// Connect to MongoDB and seed data
const seedDatabase = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/SawaikarCashew');
    console.log('✅ Connected to MongoDB');
    
    // Clear existing products
    await Product.deleteMany({});
    console.log('🗑️ Cleared existing products');
    
    // Insert sample products
    const insertedProducts = await Product.insertMany(sampleProducts);
    console.log(`✅ Inserted ${insertedProducts.length} products`);
    
    // Display inserted products
    console.log('\n📦 Seeded Products:');
    console.log('─'.repeat(50));
    insertedProducts.forEach(product => {
      console.log(`  • ${product.name} - ₹${(product.price / 100).toFixed(2)}`);
    });
    console.log('─'.repeat(50));
    
    console.log('\n🎉 Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

// Run seeder
seedDatabase();
